# Generated by Django 5.1.2 on 2025-01-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0008_osoba_wlasicicel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='wlasicicel',
            new_name='wlascicel',
        ),
    ]
