# Generated by Django 5.1.2 on 2025-01-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0009_rename_wlasicicel_osoba_wlascicel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='wlascicel',
            new_name='wlasciciel',
        ),
    ]
