# Generated by Django 5.1.2 on 2025-01-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0010_rename_wlascicel_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_person_other_owner', 'Pozwala zobaczyc modele osoba innych wlascicieli')]},
        ),
    ]
